#spring.application.name=EnterPriseEmployManagement


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=employ_management
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
   
server:
  port: 8090
  
  
  
jwt:
  secretKey: superSecretKeyForJwtShouldBeLongEnough1234567890!
  jwtExpirationTIme: 86400000


file:     
   upload-dir: D:\STS\EmployDoc